# Generated by Django 5.0.6 on 2024-06-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game', 'player')},
        ),
    ]
